name: DCI Component

on:
  pull_request:

jobs:
  action:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: DCI component
        uses: tonyskapunk/dci-component@56ac76d890f5b763aaa30e51c72cd95646aa5b35
        id: dci_component
        with:
          dciClientId: ${{ secrets.DCI_CLIENT_ID }}
          dciApiSecret: ${{ secrets.DCI_API_SECRET }}
          dciTopicVersion: 4.10"
          componentName: v1.2.3
          componentCanonicalName: "My container application"
          componentType: image
      
